//BIOLOGICAL SECTION
enum bio_warnings{
    WARNING_IRREGULAR_BLOOD_PRESSURE,
    WARNING_IRREGULAR_ECG,
    WARNING_IRREGULAR_EEG,
    WARNING_IRREGULAR_INSULINE,
    WARNING_IRREGULAR_TEMPERATURE,
    WARNING_IRREGULAR_O2_SATURATION
};

enum bio_error{
    ERROR_LOW_BLOOD_PRESSURE,
    ERROR_HIGH_BLOOD_PRESSURE,
    ERROR_HYPOGLICEMIA,
    ERROR_IPERGLICEMIA,
    ERROR_BRADYCARDIA,
    ERROR_TACHYCARDIA,
    ERROR_HYPOTERMIA,
    ERROR_IPERTERMIA,
    ERROR_LOW_OXIGEN_SATURATION
};

//MECHANICAL SECTION
enum mec_error{
    ERROR_BLOOD_SENSOR_READING,
    ERROR_EEG_SENSOR_READING,
    ERROR_ECG_SENSOR_READING,
    ERROR_INSULINE_SENSOR_READING,
    ERROR_THERMAL_PROBE_READING,
    ERROR_OXYGEN_SENSOR_READING,
    ERROR_MATRIX,
    ERROR_BOOP_SENSOR_READING
};